Feature/social login #11
So-Woo-Ju/sowooju-api-server pull request #11
Opened 2022-01-17 13:36 UTC by Sohyun-Dev

### 소셜 로그인

`.env`에 추가해주세요.
`GOOGLE_CLIENT_ID`
`GOOGLE_SECRET`
`KAKAO_KEY`
-> 노션에 공유해드렸습니다.

**1. 카카오 로그인**
`/api/v1/auth/kakao`

**2. 구글 로그인**
`/api/v1/auth/google`

2022-01-17 18:04 UTC, hocaron requested changes
LGTM👍 수고 많으셨습니다!
린트 에러 한번만 잡아주세요😁

2022-01-17 18:12 UTC, hocaron commented on src/auth/auth.docs.ts
> +        description: '로그인을 진행합니다',
description: '로그인을 진행합니다',를 ` signInWithGoogle` 설명으로 옮겨도 좋을 것 같습니다.

2022-01-17 18:12 UTC, hocaron commented on src/auth/auth.docs.ts
> +        description: '로그인을 진행합니다',
description: '로그인을 진행합니다',를 `  signInWithKakao` 설명으로 옮겨도 좋을 것 같습니다.

2022-01-17 23:19 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  @docs.signInWithGoogle('구글 OAuth2 로그인 flow 시작')
안그래도 바꿔야겠다고 생각했었는데 좋을 것 같아요!

2022-01-17 23:19 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  @docs.signInWithGoogleRedirect('구글 로그인')
반영했습니다!

2022-01-17 23:19 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  @docs.signInWithKakao('카카오 OAuth2 로그인 flow 시작')
좋습니다!!

2022-01-17 23:20 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  @docs.signInWithKakaoRedirect('카카오 로그인')
반영했습니다!

2022-01-17 23:20 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  async signInWithGoogle() { }
넵! 추가하겠습니다!

2022-01-17 23:20 UTC, Sohyun-Dev commented on src/auth/auth.controller.ts
> +  async signInWithKakao() { }
넵! 추가하겠습니다!

2022-01-17 23:20 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +      ApiBody({ type: GoogleLoginDto }),
삭제하도록 하겠습니다!

2022-01-17 23:20 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +      ApiBody({ type: KakaoLoginDto }),
삭제하도록 하겠습니다!

2022-01-17 23:21 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +      ApiCreatedResponse({
수정하겠습니다!

2022-01-17 23:21 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +      ApiCreatedResponse({
수정하겠습니다!

2022-01-17 23:22 UTC, Sohyun-Dev commented on src/auth/auth.service.ts
> +
pr 날리고 따로 해봤었는데 다른곳에서 save를 하고 있었네요..! 감사합니다! 추가하겠습니다!

2022-01-17 23:22 UTC, Sohyun-Dev commented on src/auth/strategy/google.strategy.ts
> +      user = await this.authService.validateKakao(googleId);
추가하겠습니다!

2022-01-17 23:23 UTC, Sohyun-Dev commented on src/auth/strategy/google.strategy.ts
> +    done(null, { user : user.User_id });
수정하겠습니다

2022-01-17 23:23 UTC, Sohyun-Dev commented on src/auth/strategy/kakao.strategy.ts
> +    done(null, { user : user.User_id });
수정하겠습니다.

2022-01-17 23:23 UTC, Sohyun-Dev commented on src/auth/strategy/kakao.strategy.ts
> +      user = await this.authService.validateKakao(kakaoId);
추가하겠습니다

2022-01-17 23:24 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +        description: '로그인을 진행합니다',
반영하겠습니다!

2022-01-17 23:24 UTC, Sohyun-Dev commented on src/auth/auth.docs.ts
> +        description: '로그인을 진행합니다',
반영하겠습니다!

2022-01-18 00:05 UTC, hocaron approved these changes

2022-01-18 00:11 UTC, hocaron commented
소현님! 머지하시기 전에 `npm run lint`로 에러 나는 거 한번만 잡아주시고, 머지부탁드립니다😁

2022-01-18 00:41 UTC, rlathal009 approved these changes
더 수정할 부분 없을 것 같습니다! 선우님 말씀대로 npm run lint 한번만 해서 머지 해주세요!

2022-01-18 00:57 UTC, merged